"""Pydantic domain models for THIRA.

These models represent the core data structures flowing through the THIRA loop:
decisions, plans, executions, policy verdicts, experiences, and agent results.
"""

from __future__ import annotations

from datetime import datetime
from uuid import UUID, uuid4

from pydantic import BaseModel, Field

from shared.enums import (
    AutonomyLevel,
    DecisionAction,
    ExecutionStatus,
    PlanStatus,
    RecoveryAction,
    RiskLevel,
)
from shared.enums import (
    PolicyVerdict as PolicyVerdictEnum,
)

# =============================================================
# DECISION
# =============================================================


class DecisionScores(BaseModel):
    """Multi-factor scoring for a decision."""

    urgency: float = Field(ge=0.0, le=1.0, default=0.5)
    importance: float = Field(ge=0.0, le=1.0, default=0.5)
    opportunity: float = Field(ge=0.0, le=1.0, default=0.5)
    effort: float = Field(ge=0.0, le=1.0, default=0.5)
    confidence: float = Field(ge=0.0, le=1.0, default=0.5)
    risk: float = Field(ge=0.0, le=1.0, default=0.5)
    reversibility: float = Field(ge=0.0, le=1.0, default=0.5)
    dependency: float = Field(ge=0.0, le=1.0, default=0.0)  # Are other things blocked?


class Decision(BaseModel):
    """The output of the Decision Engine."""

    id: UUID = Field(default_factory=uuid4)
    event_id: UUID
    action: DecisionAction
    scores: DecisionScores
    reasoning: str  # LLM-generated explanation of why this decision was made
    created_at: datetime = Field(default_factory=datetime.utcnow)


# =============================================================
# PLANNING
# =============================================================


class PlanStep(BaseModel):
    """A single step in a plan — maps to an agent tool invocation."""

    index: int
    description: str  # Human-readable description
    agent: str  # Which agent should handle this (e.g., "gmail", "terminal")
    tool: str  # Which tool to call (e.g., "send_email", "execute_command")
    arguments: dict = Field(default_factory=dict)
    depends_on: list[int] = Field(default_factory=list)  # Step indices this depends on
    estimated_duration_s: float | None = None


class Plan(BaseModel):
    """A plan generated by the Planning Engine — a directed acyclic graph of steps."""

    id: UUID = Field(default_factory=uuid4)
    decision_id: UUID
    goal: str
    steps: list[PlanStep]
    status: PlanStatus = PlanStatus.PENDING
    requires_approval: bool = False
    approved_at: datetime | None = None
    created_at: datetime = Field(default_factory=datetime.utcnow)
    updated_at: datetime = Field(default_factory=datetime.utcnow)


# =============================================================
# POLICY
# =============================================================


class ToolAnnotation(BaseModel):
    """Metadata attached to each MCP tool for policy decisions."""

    autonomy_level: AutonomyLevel = AutonomyLevel.L3_EXECUTE_APPROVED
    reversible: bool = True
    risk: RiskLevel = RiskLevel.LOW
    requires_confirmation: bool = False
    side_effects: list[str] = Field(default_factory=list)
    rate_limit: int | None = None  # Max calls per hour


class Action(BaseModel):
    """An action to be checked against the policy engine."""

    agent: str
    tool: str
    arguments: dict = Field(default_factory=dict)


class PolicyCheckResult(BaseModel):
    """Result of a policy check on a single action."""

    verdict: PolicyVerdictEnum
    reason: str = ""
    required_level: AutonomyLevel = AutonomyLevel.L0_OBSERVE
    granted_level: AutonomyLevel = AutonomyLevel.L0_OBSERVE


class AuthorizedPlan(BaseModel):
    """A plan that has been through the Policy Engine."""

    plan: Plan
    requires_approval: bool = False
    approval_steps: list[PlanStep] = Field(default_factory=list)
    auto_approved_steps: list[PlanStep] = Field(default_factory=list)


# =============================================================
# EXECUTION
# =============================================================


class StepResult(BaseModel):
    """Result of executing a single plan step."""

    step_index: int
    success: bool
    output: dict = Field(default_factory=dict)
    error: str | None = None
    duration_ms: int = 0
    evidence: dict = Field(default_factory=dict)  # Screenshots, logs, API responses


class RecoveryResult(BaseModel):
    """Result of a failure recovery attempt."""

    action: RecoveryAction
    reason: str
    retries_attempted: int = 0
    alternative_plan: Plan | None = None


class Execution(BaseModel):
    """Complete execution record for a plan."""

    id: UUID = Field(default_factory=uuid4)
    plan_id: UUID
    status: ExecutionStatus = ExecutionStatus.RUNNING
    step_results: list[StepResult] = Field(default_factory=list)
    recovery_results: list[RecoveryResult] = Field(default_factory=list)
    started_at: datetime = Field(default_factory=datetime.utcnow)
    completed_at: datetime | None = None
    error: str | None = None

    def record_step(self, step: PlanStep, result: StepResult) -> None:
        """Record the result of a completed step."""
        self.step_results.append(result)

    def record_recovery(self, recovery: RecoveryResult) -> None:
        """Record a recovery attempt."""
        self.recovery_results.append(recovery)

    @property
    def steps_completed(self) -> int:
        return sum(1 for r in self.step_results if r.success)

    @property
    def steps_failed(self) -> int:
        return sum(1 for r in self.step_results if not r.success)


# =============================================================
# VERIFICATION
# =============================================================


class Verification(BaseModel):
    """Result of verifying an execution's outcomes."""

    id: UUID = Field(default_factory=uuid4)
    execution_id: UUID
    passed: bool
    checks: list[VerificationCheck] = Field(default_factory=list)
    summary: str = ""
    created_at: datetime = Field(default_factory=datetime.utcnow)


class VerificationCheck(BaseModel):
    """A single verification check."""

    strategy: str  # "api_response", "screenshot", "state_check", "log_inspection"
    description: str
    expected: dict = Field(default_factory=dict)
    actual: dict = Field(default_factory=dict)
    passed: bool
    evidence_path: str | None = None  # Path to screenshot/log file
    details: str = ""


# =============================================================
# EXPERIENCE (ECHO)
# =============================================================


class Learning(BaseModel):
    """A learning extracted from an experience."""

    insight: str  # Natural language insight
    pattern: str  # What pattern was observed
    recommendation: str  # What to do differently or the same
    confidence: float = Field(ge=0.0, le=1.0, default=0.8)
    applicable_contexts: list[str] = Field(default_factory=list)


class Experience(BaseModel):
    """A complete experience record stored in ECHO.

    The fundamental data unit: Context → Decision → Action → Outcome → Learning.
    """

    id: UUID = Field(default_factory=uuid4)
    event_id: UUID
    decision_id: UUID
    plan_id: UUID | None = None
    execution_id: UUID | None = None

    context_summary: str
    decision_summary: str
    action_summary: str
    outcome_summary: str
    success: bool

    learnings: list[Learning] = Field(default_factory=list)
    created_at: datetime = Field(default_factory=datetime.utcnow)


# =============================================================
# AGENT
# =============================================================


class Capability(BaseModel):
    """A capability exposed by an agent (maps to an MCP tool)."""

    name: str
    description: str
    input_schema: dict = Field(default_factory=dict)
    annotations: ToolAnnotation = Field(default_factory=ToolAnnotation)


class AgentResult(BaseModel):
    """Result returned by an agent after executing a tool."""

    success: bool
    output: dict = Field(default_factory=dict)
    error: str | None = None
    duration_ms: int = 0
    evidence: dict = Field(default_factory=dict)


class ToolDescriptor(BaseModel):
    """Description of an available tool across the agent bus."""

    agent: str
    tool: str
    description: str
    input_schema: dict = Field(default_factory=dict)
    annotations: ToolAnnotation = Field(default_factory=ToolAnnotation)


# =============================================================
# LOOP RESULT
# =============================================================


class LoopResult(BaseModel):
    """Result of a single THIRA loop iteration."""

    status: str  # "completed", "ignored", "awaiting_approval", "failed"
    trace_id: str | None = None
    plan_id: UUID | None = None
    execution_id: UUID | None = None
    experience_id: UUID | None = None
    response: str | None = None  # Human-readable response for JARVIS
    error: str | None = None


# =============================================================
# OBSERVABILITY
# =============================================================


class LLMCallRecord(BaseModel):
    """Record of every LLM invocation for cost tracking and debugging."""

    call_id: str
    trace_id: str
    engine: str  # Which THIRA engine made the call
    model: str  # "gpt-4o", etc.
    prompt_tokens: int = 0
    completion_tokens: int = 0
    duration_ms: int = 0
    purpose: str = ""  # "entity_extraction", "decision_scoring", "plan_generation"
    cost_usd: float = 0.0


class ThiraTrace(BaseModel):
    """Complete trace of a single THIRA loop iteration."""

    trace_id: str
    trigger_event_id: UUID
    decision: Decision | None = None
    plan: Plan | None = None
    execution: Execution | None = None
    verification: Verification | None = None
    experience: Experience | None = None
    total_duration_ms: int = 0
    llm_calls: list[LLMCallRecord] = Field(default_factory=list)
    started_at: datetime = Field(default_factory=datetime.utcnow)
    completed_at: datetime | None = None
